# Generated by Django 5.2.7 on 2025-11-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Developer', 'Developer')], default='Developer', max_length=50),
        ),
    ]
